# Generated by Django 3.2.5 on 2021-07-07 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_periodos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.notas')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Nota',
                'verbose_name_plural': 'Ingreso Notas',
                'db_table': 'ingresonotas',
                'ordering': ['id'],
            },
        ),
    ]
