# Generated by Django 3.2.5 on 2021-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210706_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso_notas',
            name='nota',
            field=models.CharField(max_length=2),
        ),
    ]
